# Generated by Django 3.2.7 on 2021-09-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=20)),
                ('_identificationNumber', models.CharField(max_length=10)),
                ('_type', models.CharField(choices=[('person', 'person'), ('company', 'company')], max_length=10)),
            ],
        ),
    ]
