# Generated by Django 3.2.7 on 2021-09-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificationCadastral', models.CharField(max_length=20)),
                ('typeEstate', models.CharField(choices=[('urban', 'urban'), ('rural', 'rural')], max_length=10)),
                ('registrationNumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=20)),
                ('identificationNumber', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('person', 'person'), ('company', 'company')], max_length=10)),
            ],
        ),
    ]
