# Generated by Django 3.2.7 on 2021-09-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_identificationCadastral', models.CharField(max_length=20)),
                ('_typeEstate', models.CharField(choices=[('urban', 'urban'), ('rural', 'rural')], max_length=10)),
                ('_registrationNumber', models.CharField(max_length=20)),
            ],
        ),
    ]
