# Generated by Django 3.2.7 on 2021-09-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0002_owner_estates'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='owners',
            field=models.ManyToManyField(to='estates.Owner'),
        ),
    ]
