# Generated by Django 3.2.7 on 2021-09-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estates', '0003_estate_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='registrationNumber',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='ID',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
